### ISSUE TITLE
Get-PlatformAccount cannot enumerate Cloud Provider accounts

### ISSUE THREAD

**Issue by dkettman** [dnlrv/PlatformPlus#22]
If there are Cloud Providers defined with an IAM user, there is an issue in parsing the PlatformRowAces for those users. They are not standard users though seem to be stored in VaultAccounts alongside the other accounts. Though the permissions are not stored the same I dont think.

**Comment by dnlrv** [comment]
fixed in #23 [from dnlrv/adding-cloud-account-support,-fixin…](https://github.com/dnlrv/PlatformPlus/commit/2a21c690e700435140e60690256e11b7a4036bd2)
